print("Texto compuesto por caracteres ASCII")
print("+---------------------+")
print("|  # # ### #    ##    |")
print("|  # # # # #   #  #   |")
print("|  # # # # #   #  #   |")
print("|  ### # # #   ####   |")
print("|  # # # # #   #  #   |")
print("|  # # # # #   #  #   |")
print("|  # # ### ### #  #   |")
print("+---------------------+")
